// demo/fynapp-6-react/src/bootstrap.ts
import { FynMeshKernel, FynApp } from '@fynmesh/kernel';
import React from "react";
// @ts-ignore

import ReactDom from "esm-react-dom";
// @ts-ignore
import App from './App';

export async function bootstrap(kernel: FynMeshKernel, fynApp: FynApp) {
    console.log(`Bootstrapping ${fynApp.name}...`, React, ReactDom, "versions", React.version, ReactDom.version);

    // Find or create the div element to render into
    let targetDiv = document.getElementById('fynapp-6-react');
    if (!targetDiv) {
        targetDiv = document.createElement('div');
        targetDiv.id = 'fynapp-6-react';
        document.body.appendChild(targetDiv);
    }

    // Render the React component
    ReactDom.createRoot(targetDiv).render(React.createElement(App, { appName: fynApp.name }));

    console.log(`${fynApp.name} bootstrapped successfully`);
}

// demo/fynapp-7-solid/src/bootstrap.js
import { render } from "solid-js/web";
import App from "./App";

export async function bootstrap(kernel, fynApp) {
  console.log(`Bootstrapping ${fynApp.name}...`);

  try {
    // Find or create the div element to render into
    let targetDiv = document.getElementById("fynapp-7-solid");
    if (!targetDiv) {
      targetDiv = document.createElement("div");
      targetDiv.id = "fynapp-7-solid";
      document.body.appendChild(targetDiv);
    }

    // Clear any existing content
    targetDiv.innerHTML = "";

    // Render the Solid component
    const dispose = render(() => <App appName={fynApp.name} />, targetDiv);

    console.log(`${fynApp.name} bootstrapped successfully`);

    // Return cleanup function
    return () => {
      dispose();
      console.log(`${fynApp.name} unmounted`);
    };
  } catch (error) {
    console.error(`Error bootstrapping ${fynApp.name}:`, error);

    // Fallback rendering if component fails
    let targetDiv = document.getElementById("fynapp-7-solid");
    if (targetDiv) {
      targetDiv.innerHTML = `
        <div style="padding: 20px; color: #2D7FF9;">
          <h2>${fynApp.name} (Fallback)</h2>
          <p>Simple Solid.js component</p>
        </div>
      `;
    }
  }
}
